# Generated by Django 5.1 on 2024-08-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('En_Vogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_img_name', models.CharField(max_length=250, unique=True)),
                ('new_gallery_image', models.ImageField(blank=True, upload_to='gallery')),
            ],
        ),
    ]
