# Generated by Django 5.1 on 2024-08-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('En_Vogue', '0002_newgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
